### ISSUE TITLE
Crash when making Tinkers Sledge Hammer

### ISSUE THREAD

**Issue by Svannon** [Fundryi/Destiny#9]
When making a tinkers sledgehammer I immediatly crash and can not re enter the world.

Single Player
Pack Version 2.1.2

```Time: 4/29/18 3:38 PM
Description: Unexpected error

java.lang.NoSuchMethodError: exnihilocreatio.registries.registries.HammerRegistry.registered(Lnet/minecraft/block/Block;)Z
	at knightminer.tcomplement.plugin.exnihilo.items.ItemSledgeHammer.isEffective(ItemSledgeHammer.java:44)
	at slimeknights.tconstruct.library.utils.ToolHelper.isToolEffective2(ToolHelper.java:200)
	at slimeknights.tconstruct.library.utils.ToolHelper.calcAOEBlocks(ToolHelper.java:236)
	at slimeknights.tconstruct.library.utils.ToolHelper.calcAOEBlocks(ToolHelper.java:224)
	at slimeknights.tconstruct.library.tools.AoeToolCore.getAOEBlocks(AoeToolCore.java:23)
	at slimeknights.tconstruct.tools.common.client.RenderEvents.renderExtraBlockBreak(RenderEvents.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2233_RenderEvents_renderExtraBlockBreak_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:168)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1430)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)```

**Comment by Fundryi** [comment]
Its fixed in the dev version of ExNihiloCreatio. Will be released soon. 
Pack updated will come tomorrow probably! 
U can see @ https://github.com/BloodWorkXGaming/ExNihiloCreatio/issues/84

Sorry for this problem.
